services:
  dev:
    image: hhcmhub/xbot2-noble-dev:latest
    stdin_open: true
    tty: true 
    privileged: true
    entrypoint: /bin/bash
    restart: always
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11
      - ~/.ssh:/home/user/.ssh  # ssh
      - ./workspace:/home/user/workspace:rw  # persistent data folder
    environment:
      - TERM=xterm-256color

  dev-nvidia:
    extends: dev
    environment:
      - DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  robot:
    extends: dev
    image: hhcmhub/xbot2-noble-robot:latest
  
  robot-nvidia:
    extends: dev-nvidia
    image: hhcmhub/xbot2-noble-robot:latest

  rt-v5:
    extends: dev
    image: hhcmhub/xbot2-noble-rt-v5:latest

  rt-v6:
    extends: dev
    image: hhcmhub/xbot2-noble-rt-v6:latest

  rt:
    extends: rt-v6

