services:
  base:
    image: ${BASE_IMAGE_NAME}-base:${TAGNAME}
    build:
      dockerfile: Dockerfile-base
      secrets: [netrc]
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        ROBOT_NAME: ${ROBOT_NAME}
        RECIPES_TAG: ${RECIPES_TAG}
        KERNEL_VER: ${KERNEL_VER}
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME}
        ROBOT_PACKAGES: ${ROBOT_PACKAGES}
        ADDITIONAL_PACKAGES: ${ADDITIONAL_PACKAGES}
        RECIPES_REPO: ${RECIPES_REPO}
        ROBOT_CONFIG_PATH: ${ROBOT_CONFIG_PATH}

  xeno:
    image: ${BASE_IMAGE_NAME}-xeno-v${KERNEL_VER}:${TAGNAME}
    build:
      dockerfile: Dockerfile-xeno
      secrets: [netrc]
      args:
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME}
        TAGNAME: ${TAGNAME}
        KERNEL_VER: ${KERNEL_VER}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        ROBOT_PACKAGES: ${ROBOT_PACKAGES}
        ADDITIONAL_PACKAGES: ${ADDITIONAL_PACKAGES}
        RECIPES_TAG: ${RECIPES_TAG}
        ROBOT_CONFIG_PATH: ${ROBOT_CONFIG_PATH}
    depends_on:
      - base

  locomotion:
    image: ${BASE_IMAGE_NAME}-locomotion:${TAGNAME}
    build:
      dockerfile: Dockerfile-locomotion
      secrets: [netrc]
      args:
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME}  # This overrides the default
        TAGNAME: ${TAGNAME}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        ROBOT_NAME: ${ROBOT_NAME}
        RECIPES_TAG: ${RECIPES_TAG}
        KERNEL_VER: ${KERNEL_VER}
        ROBOT_PACKAGES: ${ROBOT_PACKAGES}
        ADDITIONAL_PACKAGES: ${ADDITIONAL_PACKAGES}
        ROBOT_CONFIG_PATH: ${ROBOT_CONFIG_PATH}
    depends_on:
      - base
secrets:
  netrc:
    file: ~/.netrc