services:
  base:
    image: ${DOCKER_REGISTRY}/${BASE_IMAGE_NAME}-base:${TAGNAME}
    build:
      context: .
      dockerfile: Dockerfile-base
      secrets: [netrc]
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        ROBOT_NAME: ${ROBOT_NAME}
        RECIPES_TAG: ${RECIPES_TAG}
        KERNEL_VER: ${KERNEL_VER}
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME}
        ROBOT_PACKAGES: ${ROBOT_PACKAGES}
        ADDITIONAL_PACKAGES: ${ADDITIONAL_PACKAGES}
       

  xeno:
    image: ${DOCKER_REGISTRY}/${BASE_IMAGE_NAME}-xeno-v${KERNEL_VER}:${TAGNAME}
    build:
      context: .
      dockerfile: Dockerfile-xeno
      secrets: [netrc]
      args:
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME}
        KERNEL_VER: ${KERNEL_VER}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        ROBOT_PACKAGES: ${ROBOT_PACKAGES}
        ADDITIONAL_PACKAGES: ${ADDITIONAL_PACKAGES}
        RECIPES_TAG: ${RECIPES_TAG}
    depends_on:
      - base

  locomotion:
    image: ${DOCKER_REGISTRY}/${BASE_IMAGE_NAME}-locomotion:${TAGNAME}
    build:
      context: .
      dockerfile: Dockerfile-locomotion
      secrets: [netrc]
      args:
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME}  # This overrides the default
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        ROBOT_NAME: ${ROBOT_NAME}
        RECIPES_TAG: ${RECIPES_TAG}
        KERNEL_VER: ${KERNEL_VER}
        ROBOT_PACKAGES: ${ROBOT_PACKAGES}
        ADDITIONAL_PACKAGES: ${ADDITIONAL_PACKAGES}
    depends_on:
      - base
secrets:
  netrc:
    file: ~/.netrc