ARG BASE_IMAGE_NAME=robot-cetc-focal-ros1

FROM ${BASE_IMAGE_NAME}-base

# Build arguments - these come from the robot config (e.g., kyon-config.env)
ARG USER_ID=1000
ARG KERNEL_VER=0
ARG USER_NAME=user
ARG ROBOT_NAME=robot
ARG RECIPES_TAG=main

# env
ENV PYTHONUNBUFFERED=1

USER root

# build required software (requires valid netrc for auth)
RUN apt-get update && apt-get install -y sudo build-essential gfortran \
    git curl python3-tk python3-pip libjpeg-dev wget patchelf nano libglfw3-dev \
    libassimp-dev liblapack-dev libblas-dev libyaml-cpp-dev libmatio-dev \
    swig clang ros-noetic-catkin ros-noetic-joy graphviz-dev

# upgrade pip and install the latest version of NumPy 
# only required for ROS noetic
RUN pip install numpy scipy numpy_ros matplotlib colorama Cython networkx pygraphviz
    
USER ${USER_NAME}

# Set environment variables for the build
ENV RECIPES_TAG=$RECIPES_TAG

# grow - using configurable recipes tag instead of hardcoded "kyon-cetc"
RUN echo 1 && cd ~/xbot2_ws/recipes/multidof_recipes && git pull origin ${RECIPES_TAG}

WORKDIR /home/${USER_NAME}/xbot2_ws

RUN --mount=type=secret,id=netrc,dst=/home/$USER_NAME/.netrc,uid=$USER_ID \ 
    forest grow pybind11 -j20 && \
    forest grow casadi -j20 --clone-depth 1 -v && \
    forest grow pinocchio -j20 --clone-depth 1 -v && \
    forest grow casadi_kin_dyn -j20 -v && \
    forest grow horizon -j20 -v && \
    forest grow phase_manager -j20 -v && \
    forest grow ${ROBOT_NAME}_controller -j20 -v && \
    rm -rf build src/pinocchio src/casadi src/horizon/horizon/external_libs/*

RUN --mount=type=secret,id=netrc,dst=/home/$USER_NAME/.netrc,uid=$USER_ID echo "Locomotion build completed"