# THIS ARG MUST COME BEFORE FROM
ARG DOCKER_REGISTRY=hhcmhub
ARG BASE_IMAGE_NAME=robot-focal-ros1
ARG TAGNAME=v1.0.0

FROM base

# get kernel version
ARG KERNEL_VER=0
ARG USER_ID=1000
ARG USER_NAME=user
ARG ROBOT_PACKAGES=""
ARG ADDITIONAL_PACKAGES=""
ARG RECIPES_TAG=main
ARG ROBOT_NAME=robot
ENV ROBOT_NAME=${ROBOT_NAME}

RUN echo "KERNEL_VER = $KERNEL_VER"

# remove xbot2
RUN sudo apt remove -y xbot2
# remove xbot2
USER root

# Run the update and install commands (no sudo needed now)
RUN apt-get update && apt-get install -y --no-install-recommends build-essential libtool

# Switch back to your non-root user 
# The USER_NAME variable should be available from your build args
USER ${USER_NAME}

# build required software (requires valid netrc for auth) 
RUN --mount=type=secret,id=netrc,dst=/home/$USER_NAME/.netrc,uid=$USER_ID /bin/bash scripts/build-xeno.bash

# xenomai from regular user
RUN sudo groupadd -f xenomai -g 1001
RUN sudo usermod -a -G xenomai $USER_NAME

# tty from regular user
RUN sudo usermod -a -G dialout $USER_NAME
